rm -f ./truth/truth*.dat
rm -f ./obs/truth*.dat
rm -f ./obs/obs*.dat
rm -f ./fsc/*.dat
rm -f ./bgd/*.dat
rm -f ./ana/*.dat
rm -f ./ini/bgd_*.dat
rm -f ./letkf/letkf*.dat
rm -f ./letkf/ana*.dat
rm -f ./letkf/obs*.dat
rm -f ./letkf/bgd*.dat
rm -f ./dig/ana0*.dat
rm -f ./dig/bgd0*.dat
rm -f ./dig/ctl0*.dat
rm -f ./dig/obs0*.dat
rm -f ./dig/truth*.dat
